import { TableProfile } from './types';

// Sales Detailed Table Profile
export const salesDetailedProfile: TableProfile = {
  tableName: 'sales_detailed',
  rowCount: 45230,
  columnCount: 18,
  missingPercentage: 2.3,
  lastUpdated: '2025-12-31',
  duplicateRows: 0,
  hasOutliers: true,
  columnRoleDistribution: {
    dimensions: 8,
    measures: 7,
    temporal: 3,
  },
  columns: [
    {
      name: 'transaction_id',
      role: 'dimension',
      dataType: 'string',
      nullPercentage: 0,
      uniqueCount: 45230,
      totalCount: 45230,
      cardinality: 'high',
    },
    {
      name: 'customer_id',
      role: 'dimension',
      dataType: 'string',
      nullPercentage: 0,
      uniqueCount: 2450,
      totalCount: 45230,
      cardinality: 'high',
      topValues: [
        { value: 'C001234', count: 89 },
        { value: 'C002341', count: 76 },
        { value: 'C003412', count: 72 },
        { value: 'C004123', count: 68 },
        { value: 'C005231', count: 65 },
      ],
    },
    {
      name: 'store_id',
      role: 'dimension',
      dataType: 'string',
      nullPercentage: 0,
      uniqueCount: 6,
      totalCount: 45230,
      cardinality: 'low',
      topValues: [
        { value: 'S001', count: 9840 },
        { value: 'S002', count: 8920 },
        { value: 'S003', count: 8450 },
        { value: 'S004', count: 7230 },
        { value: 'S005', count: 5890 },
        { value: 'S006', count: 4900 },
      ],
      suggestedCharts: [
        { type: 'bar', title: 'Sales by Store', xAxis: 'store_id', yAxis: 'revenue' },
        { type: 'pie', title: 'Store Distribution', xAxis: 'store_id' },
      ],
    },
    {
      name: 'channel',
      role: 'dimension',
      dataType: 'string',
      nullPercentage: 0,
      uniqueCount: 2,
      totalCount: 45230,
      cardinality: 'low',
      topValues: [
        { value: 'Store', count: 28340 },
        { value: 'Online', count: 16890 },
      ],
      suggestedCharts: [
        { type: 'pie', title: 'Channel Split', xAxis: 'channel' },
        { type: 'bar', title: 'Revenue by Channel', xAxis: 'channel', yAxis: 'revenue' },
      ],
    },
    {
      name: 'category',
      role: 'dimension',
      dataType: 'string',
      nullPercentage: 0,
      uniqueCount: 12,
      totalCount: 45230,
      cardinality: 'medium',
      topValues: [
        { value: 'Electronics', count: 12340 },
        { value: 'Apparel', count: 9870 },
        { value: 'Home & Garden', count: 7650 },
        { value: 'Sports', count: 5430 },
        { value: 'Beauty', count: 4320 },
      ],
    },
    {
      name: 'product_id',
      role: 'dimension',
      dataType: 'string',
      nullPercentage: 0,
      uniqueCount: 148,
      totalCount: 45230,
      cardinality: 'high',
    },
    {
      name: 'sku_id',
      role: 'dimension',
      dataType: 'string',
      nullPercentage: 0,
      uniqueCount: 150,
      totalCount: 45230,
      cardinality: 'high',
    },
    {
      name: 'salesperson_id',
      role: 'dimension',
      dataType: 'string',
      nullPercentage: 12.5,
      uniqueCount: 26,
      totalCount: 45230,
      cardinality: 'medium',
    },
    {
      name: 'quantity',
      role: 'measure',
      dataType: 'integer',
      nullPercentage: 0,
      uniqueCount: 15,
      totalCount: 45230,
      min: 1,
      max: 12,
      mean: 2.3,
      median: 2,
      outlierCount: 234,
      histogram: [
        { bin: '1', count: 18500 },
        { bin: '2', count: 12300 },
        { bin: '3', count: 7200 },
        { bin: '4', count: 3800 },
        { bin: '5+', count: 3430 },
      ],
    },
    {
      name: 'unit_price',
      role: 'measure',
      dataType: 'decimal',
      nullPercentage: 0,
      uniqueCount: 890,
      totalCount: 45230,
      min: 4.99,
      max: 1299.99,
      mean: 87.45,
      median: 54.99,
      outlierCount: 156,
    },
    {
      name: 'revenue',
      role: 'measure',
      dataType: 'decimal',
      nullPercentage: 0,
      uniqueCount: 4230,
      totalCount: 45230,
      min: 4.99,
      max: 7899.94,
      mean: 201.34,
      median: 124.50,
      outlierCount: 423,
      histogram: [
        { bin: '0-50', count: 12340 },
        { bin: '50-100', count: 9870 },
        { bin: '100-200', count: 11230 },
        { bin: '200-500', count: 8430 },
        { bin: '500+', count: 3360 },
      ],
    },
    {
      name: 'discount_percent',
      role: 'measure',
      dataType: 'decimal',
      nullPercentage: 0,
      uniqueCount: 45,
      totalCount: 45230,
      min: 0,
      max: 45,
      mean: 8.7,
      median: 5,
      outlierCount: 890,
    },
    {
      name: 'gross_margin',
      role: 'measure',
      dataType: 'decimal',
      nullPercentage: 0,
      uniqueCount: 3120,
      totalCount: 45230,
      min: -234.50,
      max: 4567.89,
      mean: 67.23,
      median: 42.10,
      outlierCount: 567,
    },
    {
      name: 'cost',
      role: 'measure',
      dataType: 'decimal',
      nullPercentage: 0,
      uniqueCount: 2340,
      totalCount: 45230,
      min: 2.99,
      max: 890.00,
      mean: 52.34,
      median: 34.99,
      outlierCount: 234,
    },
    {
      name: 'is_returned',
      role: 'dimension',
      dataType: 'boolean',
      nullPercentage: 0,
      uniqueCount: 2,
      totalCount: 45230,
      cardinality: 'low',
      topValues: [
        { value: 'false', count: 40230 },
        { value: 'true', count: 5000 },
      ],
    },
    {
      name: 'transaction_date',
      role: 'temporal',
      dataType: 'date',
      nullPercentage: 0,
      uniqueCount: 365,
      totalCount: 45230,
      minDate: '2025-01-01',
      maxDate: '2025-12-31',
      granularity: 'day',
      timeSeriesData: [
        { date: '2025-01', count: 3245 },
        { date: '2025-02', count: 3120 },
        { date: '2025-03', count: 3567 },
        { date: '2025-04', count: 3890 },
        { date: '2025-05', count: 3456 },
        { date: '2025-06', count: 3234 },
        { date: '2025-07', count: 3678 },
        { date: '2025-08', count: 3890 },
        { date: '2025-09', count: 4123 },
        { date: '2025-10', count: 4567 },
        { date: '2025-11', count: 4890 },
        { date: '2025-12', count: 3570 },
      ],
      suggestedCharts: [
        { type: 'line', title: 'Sales Over Time', xAxis: 'transaction_date', yAxis: 'revenue' },
      ],
    },
    {
      name: 'order_date',
      role: 'temporal',
      dataType: 'timestamp',
      nullPercentage: 0,
      uniqueCount: 8760,
      totalCount: 45230,
      minDate: '2025-01-01T00:00:00',
      maxDate: '2025-12-31T23:59:59',
      granularity: 'day',
    },
    {
      name: 'ship_date',
      role: 'temporal',
      dataType: 'date',
      nullPercentage: 15.2,
      uniqueCount: 365,
      totalCount: 45230,
      minDate: '2025-01-02',
      maxDate: '2026-01-05',
      granularity: 'day',
    },
  ],
  keyInsights: [
    'Online channel shows 42% growth over the year, now representing 37% of total sales',
    'Top 10 hero SKUs account for 45% of total revenue (strong Pareto effect)',
    'Stores S005 and S006 are underperforming with 23% lower revenue per transaction',
    'Discount-heavy transactions (>20%) show 34% margin erosion',
    'Q4 shows seasonal peak with 28% higher transaction volume',
  ],
  suggestedQuestions: [
    'Which products drive the most revenue?',
    'How do online vs store sales compare?',
    'Which stores are underperforming?',
    'What is the impact of discounts on margins?',
    'What are the peak sales periods?',
  ],
};

// Customer 360 Table Profile
export const customer360Profile: TableProfile = {
  tableName: 'customer_360',
  rowCount: 2500,
  columnCount: 14,
  missingPercentage: 1.8,
  lastUpdated: '2025-12-31',
  duplicateRows: 0,
  hasOutliers: true,
  columnRoleDistribution: {
    dimensions: 6,
    measures: 6,
    temporal: 2,
  },
  columns: [
    {
      name: 'customer_id',
      role: 'dimension',
      dataType: 'string',
      nullPercentage: 0,
      uniqueCount: 2500,
      totalCount: 2500,
      cardinality: 'high',
    },
    {
      name: 'segment',
      role: 'dimension',
      dataType: 'string',
      nullPercentage: 0,
      uniqueCount: 4,
      totalCount: 2500,
      cardinality: 'low',
      topValues: [
        { value: 'Consumer', count: 1250 },
        { value: 'Corporate', count: 650 },
        { value: 'Home Office', count: 400 },
        { value: 'Small Business', count: 200 },
      ],
      suggestedCharts: [
        { type: 'pie', title: 'Customer Segments', xAxis: 'segment' },
        { type: 'bar', title: 'Revenue by Segment', xAxis: 'segment', yAxis: 'total_spent' },
      ],
    },
    {
      name: 'loyalty_tier',
      role: 'dimension',
      dataType: 'string',
      nullPercentage: 0,
      uniqueCount: 4,
      totalCount: 2500,
      cardinality: 'low',
      topValues: [
        { value: 'Bronze', count: 1500 },
        { value: 'Silver', count: 600 },
        { value: 'Gold', count: 300 },
        { value: 'Platinum', count: 100 },
      ],
    },
    {
      name: 'region',
      role: 'dimension',
      dataType: 'string',
      nullPercentage: 0,
      uniqueCount: 6,
      totalCount: 2500,
      cardinality: 'low',
      topValues: [
        { value: 'Northeast', count: 620 },
        { value: 'West', count: 580 },
        { value: 'South', count: 520 },
        { value: 'Midwest', count: 450 },
        { value: 'Southeast', count: 330 },
      ],
    },
    {
      name: 'preferred_channel',
      role: 'dimension',
      dataType: 'string',
      nullPercentage: 0,
      uniqueCount: 2,
      totalCount: 2500,
      cardinality: 'low',
      topValues: [
        { value: 'Store', count: 1580 },
        { value: 'Online', count: 920 },
      ],
    },
    {
      name: 'is_high_return',
      role: 'dimension',
      dataType: 'boolean',
      nullPercentage: 0,
      uniqueCount: 2,
      totalCount: 2500,
      cardinality: 'low',
      topValues: [
        { value: 'false', count: 2350 },
        { value: 'true', count: 150 },
      ],
    },
    {
      name: 'total_spent',
      role: 'measure',
      dataType: 'decimal',
      nullPercentage: 0,
      uniqueCount: 2480,
      totalCount: 2500,
      min: 24.99,
      max: 45678.90,
      mean: 3245.67,
      median: 1890.45,
      outlierCount: 89,
      histogram: [
        { bin: '0-500', count: 450 },
        { bin: '500-1000', count: 520 },
        { bin: '1000-2500', count: 680 },
        { bin: '2500-5000', count: 450 },
        { bin: '5000+', count: 400 },
      ],
    },
    {
      name: 'total_orders',
      role: 'measure',
      dataType: 'integer',
      nullPercentage: 0,
      uniqueCount: 85,
      totalCount: 2500,
      min: 1,
      max: 89,
      mean: 18.1,
      median: 12,
      outlierCount: 45,
    },
    {
      name: 'avg_order_value',
      role: 'measure',
      dataType: 'decimal',
      nullPercentage: 0,
      uniqueCount: 890,
      totalCount: 2500,
      min: 15.99,
      max: 567.89,
      mean: 124.56,
      median: 98.45,
      outlierCount: 67,
    },
    {
      name: 'return_rate',
      role: 'measure',
      dataType: 'decimal',
      nullPercentage: 0,
      uniqueCount: 45,
      totalCount: 2500,
      min: 0,
      max: 0.45,
      mean: 0.11,
      median: 0.08,
      outlierCount: 150,
    },
    {
      name: 'lifetime_value',
      role: 'measure',
      dataType: 'decimal',
      nullPercentage: 0,
      uniqueCount: 2450,
      totalCount: 2500,
      min: 12.50,
      max: 34567.89,
      mean: 2456.78,
      median: 1567.90,
      outlierCount: 78,
    },
    {
      name: 'avg_discount_taken',
      role: 'measure',
      dataType: 'decimal',
      nullPercentage: 0,
      uniqueCount: 35,
      totalCount: 2500,
      min: 0,
      max: 0.35,
      mean: 0.12,
      median: 0.10,
      outlierCount: 56,
    },
    {
      name: 'first_purchase_date',
      role: 'temporal',
      dataType: 'date',
      nullPercentage: 0,
      uniqueCount: 365,
      totalCount: 2500,
      minDate: '2025-01-01',
      maxDate: '2025-12-31',
      granularity: 'day',
    },
    {
      name: 'last_purchase_date',
      role: 'temporal',
      dataType: 'date',
      nullPercentage: 0,
      uniqueCount: 365,
      totalCount: 2500,
      minDate: '2025-01-15',
      maxDate: '2025-12-31',
      granularity: 'day',
    },
  ],
  keyInsights: [
    'Platinum tier customers (4%) generate 28% of total revenue',
    '6% of customers are high-return, causing 23% of all returns',
    'Online-preferred customers have 18% higher AOV than store-preferred',
    'Corporate segment shows highest lifetime value at $4,567 average',
    'Customer acquisition is strongest in Q1 and Q4',
  ],
  suggestedQuestions: [
    'Who are the most valuable customers?',
    'Which segment has the highest return rate?',
    'How does loyalty tier affect spending?',
    'What drives customer lifetime value?',
    'Which regions show strongest growth?',
  ],
};

// Store Daily Performance Profile
export const storeDailyPerformanceProfile: TableProfile = {
  tableName: 'store_daily_performance',
  rowCount: 2190,
  columnCount: 12,
  missingPercentage: 0.5,
  lastUpdated: '2025-12-31',
  duplicateRows: 0,
  hasOutliers: true,
  columnRoleDistribution: {
    dimensions: 3,
    measures: 8,
    temporal: 1,
  },
  columns: [
    {
      name: 'store_id',
      role: 'dimension',
      dataType: 'string',
      nullPercentage: 0,
      uniqueCount: 6,
      totalCount: 2190,
      cardinality: 'low',
      topValues: [
        { value: 'S001', count: 365 },
        { value: 'S002', count: 365 },
        { value: 'S003', count: 365 },
        { value: 'S004', count: 365 },
        { value: 'S005', count: 365 },
        { value: 'S006', count: 365 },
      ],
      suggestedCharts: [
        { type: 'bar', title: 'Daily Revenue by Store', xAxis: 'store_id', yAxis: 'daily_revenue' },
      ],
    },
    {
      name: 'store_name',
      role: 'dimension',
      dataType: 'string',
      nullPercentage: 0,
      uniqueCount: 6,
      totalCount: 2190,
      cardinality: 'low',
      topValues: [
        { value: 'SilkRoute NYC Flagship', count: 365 },
        { value: 'SilkRoute LA Premium', count: 365 },
        { value: 'SilkRoute Chicago Central', count: 365 },
        { value: 'SilkRoute Miami Beach', count: 365 },
        { value: 'SilkRoute Denver Outlet', count: 365 },
        { value: 'SilkRoute Seattle Express', count: 365 },
      ],
    },
    {
      name: 'region',
      role: 'dimension',
      dataType: 'string',
      nullPercentage: 0,
      uniqueCount: 6,
      totalCount: 2190,
      cardinality: 'low',
      topValues: [
        { value: 'Northeast', count: 365 },
        { value: 'West', count: 730 },
        { value: 'Midwest', count: 365 },
        { value: 'South', count: 365 },
        { value: 'Northwest', count: 365 },
      ],
    },
    {
      name: 'date',
      role: 'temporal',
      dataType: 'date',
      nullPercentage: 0,
      uniqueCount: 365,
      totalCount: 2190,
      minDate: '2025-01-01',
      maxDate: '2025-12-31',
      granularity: 'day',
      timeSeriesData: [
        { date: '2025-01', count: 186 },
        { date: '2025-02', count: 168 },
        { date: '2025-03', count: 186 },
        { date: '2025-04', count: 180 },
        { date: '2025-05', count: 186 },
        { date: '2025-06', count: 180 },
        { date: '2025-07', count: 186 },
        { date: '2025-08', count: 186 },
        { date: '2025-09', count: 180 },
        { date: '2025-10', count: 186 },
        { date: '2025-11', count: 180 },
        { date: '2025-12', count: 186 },
      ],
    },
    {
      name: 'daily_revenue',
      role: 'measure',
      dataType: 'decimal',
      nullPercentage: 0,
      uniqueCount: 2150,
      totalCount: 2190,
      min: 1234.56,
      max: 45678.90,
      mean: 12456.78,
      median: 11234.56,
      outlierCount: 89,
      histogram: [
        { bin: '0-5000', count: 234 },
        { bin: '5000-10000', count: 567 },
        { bin: '10000-15000', count: 789 },
        { bin: '15000-25000', count: 456 },
        { bin: '25000+', count: 144 },
      ],
    },
    {
      name: 'transaction_count',
      role: 'measure',
      dataType: 'integer',
      nullPercentage: 0,
      uniqueCount: 120,
      totalCount: 2190,
      min: 12,
      max: 234,
      mean: 68.5,
      median: 62,
      outlierCount: 34,
    },
    {
      name: 'avg_basket_size',
      role: 'measure',
      dataType: 'decimal',
      nullPercentage: 0,
      uniqueCount: 890,
      totalCount: 2190,
      min: 45.67,
      max: 234.56,
      mean: 124.56,
      median: 118.90,
      outlierCount: 45,
    },
    {
      name: 'foot_traffic',
      role: 'measure',
      dataType: 'integer',
      nullPercentage: 0,
      uniqueCount: 450,
      totalCount: 2190,
      min: 89,
      max: 1234,
      mean: 456.78,
      median: 423,
      outlierCount: 56,
    },
    {
      name: 'conversion_rate',
      role: 'measure',
      dataType: 'decimal',
      nullPercentage: 0,
      uniqueCount: 78,
      totalCount: 2190,
      min: 0.08,
      max: 0.35,
      mean: 0.18,
      median: 0.17,
      outlierCount: 23,
    },
    {
      name: 'avg_discount_percent',
      role: 'measure',
      dataType: 'decimal',
      nullPercentage: 0,
      uniqueCount: 45,
      totalCount: 2190,
      min: 0.02,
      max: 0.28,
      mean: 0.11,
      median: 0.10,
      outlierCount: 67,
    },
    {
      name: 'gross_margin',
      role: 'measure',
      dataType: 'decimal',
      nullPercentage: 0,
      uniqueCount: 1890,
      totalCount: 2190,
      min: 234.56,
      max: 12345.67,
      mean: 4567.89,
      median: 4123.45,
      outlierCount: 78,
    },
    {
      name: 'stockout_incidents',
      role: 'measure',
      dataType: 'integer',
      nullPercentage: 0,
      uniqueCount: 15,
      totalCount: 2190,
      min: 0,
      max: 12,
      mean: 2.3,
      median: 2,
      outlierCount: 89,
    },
  ],
  keyInsights: [
    'NYC Flagship generates 28% more revenue than average store',
    'Denver Outlet and Seattle Express show 23% lower conversion rates',
    'Discount-heavy stores (S005, S006) have 34% lower gross margins',
    'Weekend traffic is 45% higher than weekdays across all stores',
    'Q4 shows 35% revenue increase with stockout incidents also peaking',
  ],
  suggestedQuestions: [
    'Which store has the best performance?',
    'How does foot traffic correlate with revenue?',
    'Which stores have high discount rates?',
    'When do stockouts most commonly occur?',
    'What drives conversion rate differences?',
  ],
};

// Export all profiles as a map
export const tableProfiles: Record<string, TableProfile> = {
  sales_detailed: salesDetailedProfile,
  customer_360: customer360Profile,
  store_daily_performance: storeDailyPerformanceProfile,
};
