"""Minimal KPI risk alert checker using decision signals as source of truth."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from sqlalchemy.orm import Session

from app.core.config import get_settings
from app.services.alerts_minimal.email_sender import EmailSender
from app.services.alerts_minimal.state_store import AlertStateStore
from app.services.strategy.decision_signals import build_decision_surface


@dataclass(frozen=True)
class AlertCheckResult:
    """Outcome for a single alert check run."""

    dataset_id: str
    alert_triggered: bool
    email_sent: bool
    dry_run: bool
    reason: str
    transition_count: int
    revision: str | None
    generated_at: str | None


def _severity_map(signals: list[dict[str, Any]]) -> dict[str, str]:
    output: dict[str, str] = {}
    for item in signals:
        signal_id = str(item.get("id") or "").strip()
        severity = str(item.get("severity") or "").strip().lower()
        if not signal_id:
            continue
        output[signal_id] = severity
    return output


def detect_critical_transitions(
    previous_severity_by_signal: dict[str, str],
    current_signals: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    """Return signals that became critical in this run."""
    transitions: list[dict[str, Any]] = []
    for item in current_signals:
        signal_id = str(item.get("id") or "").strip()
        severity = str(item.get("severity") or "").strip().lower()
        if not signal_id or severity != "critical":
            continue

        previous = previous_severity_by_signal.get(signal_id, "")
        if previous != "critical":
            transitions.append(item)
    return transitions


def _format_signal_lines(signals: list[dict[str, Any]]) -> str:
    def _clean(value: str) -> str:
        return " ".join(value.split())

    def _trim(value: str, *, limit: int) -> str:
        text = _clean(value)
        if len(text) <= limit:
            return text
        return text[: limit - 3].rstrip() + "..."

    lines: list[str] = []
    max_items = 5
    visible = signals[:max_items]

    for index, item in enumerate(visible, start=1):
        title = str(item.get("title") or "Untitled signal")
        explanation = str(item.get("explanation") or "")
        action = str(item.get("suggested_action") or "")
        lines.append(f"{index}. {title}")
        if explanation:
            lines.append(f"   Why: {_trim(explanation, limit=180)}")
        if action:
            lines.append(f"   Action: {_trim(action, limit=140)}")
        lines.append("")

    remaining = len(signals) - len(visible)
    if remaining > 0:
        lines.append(f"...and {remaining} more critical signal(s).")

    return "\n".join(lines).rstrip()


def build_alert_message(
    *,
    dataset_id: str,
    revision: str | None,
    generated_at: str | None,
    transitioned_critical_signals: list[dict[str, Any]],
) -> tuple[str, str]:
    subject = f"[ContinuumAI Alert] Critical KPI risk update for {dataset_id}"
    body = (
        "ContinuumAI detected a KPI risk escalation.\n\n"
        "Summary\n"
        "-------\n"
        f"Dataset: {dataset_id}\n"
        f"Revision: {revision or 'n/a'}\n"
        f"Generated at: {generated_at or 'n/a'}\n"
        f"New/Escalated critical signals: {len(transitioned_critical_signals)}\n\n"
        "Critical signal details\n"
        "-----------------------\n"
        f"{_format_signal_lines(transitioned_critical_signals)}\n\n"
        "This alert was generated by ContinuumAI alerts_minimal MVP."
    )
    return subject, body


def _parse_recipients(raw: str | None) -> list[str]:
    if not raw:
        return []
    return [item.strip() for item in raw.split(",") if item.strip()]


def run_alert_check(
    *,
    dataset_id: str,
    db: Session,
    dry_run: bool = False,
    force: bool = False,
    update_state_in_dry_run: bool = False,
    settings: Any | None = None,
) -> AlertCheckResult:
    settings = settings or get_settings()

    if not dry_run and not bool(getattr(settings, "ALERTS_ENABLED", False)):
        return AlertCheckResult(
            dataset_id=dataset_id,
            alert_triggered=False,
            email_sent=False,
            dry_run=dry_run,
            reason="alerts_disabled",
            transition_count=0,
            revision=None,
            generated_at=None,
        )

    decision_surface = build_decision_surface(dataset_id=dataset_id, db=db)
    current_signals = list(decision_surface.get("decision_signals", []))
    current_severity = _severity_map(current_signals)

    state_store = AlertStateStore(str(getattr(settings, "ALERT_STATE_FILE", "out/alerts_state.json")))
    previous_state = state_store.get_dataset_state(dataset_id)
    previous_severity = previous_state.get("severity_by_signal", {})
    if not isinstance(previous_severity, dict):
        previous_severity = {}

    transitions = detect_critical_transitions(previous_severity, current_signals)
    should_alert = force or len(transitions) > 0

    revision = decision_surface.get("revision")
    generated_at = decision_surface.get("generated_at")

    if not should_alert:
        state_store.update_dataset_state(
            dataset_id=dataset_id,
            revision=revision if isinstance(revision, str) else None,
            generated_at=generated_at if isinstance(generated_at, str) else None,
            severity_by_signal=current_severity,
        )
        return AlertCheckResult(
            dataset_id=dataset_id,
            alert_triggered=False,
            email_sent=False,
            dry_run=dry_run,
            reason="no_escalation",
            transition_count=0,
            revision=revision if isinstance(revision, str) else None,
            generated_at=generated_at if isinstance(generated_at, str) else None,
        )

    alert_signals = transitions if transitions else [
        item for item in current_signals if str(item.get("severity") or "").strip().lower() == "critical"
    ]

    subject, body = build_alert_message(
        dataset_id=dataset_id,
        revision=revision if isinstance(revision, str) else None,
        generated_at=generated_at if isinstance(generated_at, str) else None,
        transitioned_critical_signals=alert_signals,
    )

    recipients = _parse_recipients(getattr(settings, "ALERT_EMAIL_TO", None))
    if not recipients:
        return AlertCheckResult(
            dataset_id=dataset_id,
            alert_triggered=False,
            email_sent=False,
            dry_run=dry_run,
            reason="missing_recipients",
            transition_count=len(transitions),
            revision=revision if isinstance(revision, str) else None,
            generated_at=generated_at if isinstance(generated_at, str) else None,
        )

    email_sent = False
    if not dry_run:
        sender = EmailSender(
            host=str(getattr(settings, "SMTP_HOST", "")),
            port=int(getattr(settings, "SMTP_PORT", 587)),
            username=getattr(settings, "SMTP_USER", None),
            password=getattr(settings, "SMTP_PASSWORD", None),
            use_tls=bool(getattr(settings, "SMTP_USE_TLS", True)),
            from_address=str(getattr(settings, "ALERT_EMAIL_FROM", "")),
        )
        sender.send(to_addresses=recipients, subject=subject, body=body)
        email_sent = True

    if not dry_run or update_state_in_dry_run:
        state_store.update_dataset_state(
            dataset_id=dataset_id,
            revision=revision if isinstance(revision, str) else None,
            generated_at=generated_at if isinstance(generated_at, str) else None,
            severity_by_signal=current_severity,
        )

    return AlertCheckResult(
        dataset_id=dataset_id,
        alert_triggered=True,
        email_sent=email_sent,
        dry_run=dry_run,
        reason="force" if force and len(transitions) == 0 else "critical_transition",
        transition_count=len(transitions),
        revision=revision if isinstance(revision, str) else None,
        generated_at=generated_at if isinstance(generated_at, str) else None,
    )
