apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: continuum-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: backend
          image: ghcr.io/OWNER/backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DATABASE_URL
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET_KEY
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: OPENAI_API_KEY
                  optional: true
            - name: ALERT_EMAIL_TO
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: ALERT_EMAIL_TO
                  optional: true
            - name: ALERT_EMAIL_FROM
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: ALERT_EMAIL_FROM
                  optional: true
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SMTP_USER
                  optional: true
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SMTP_PASSWORD
                  optional: true
            - name: JWT_ALGORITHM
              value: "HS256"
            - name: ACCESS_TOKEN_EXPIRE_MINUTES
              value: "30"
            - name: FRONTEND_URL
              value: "http://localhost"
            - name: OPENAI_MODEL
              value: "gpt-4o-mini"
            - name: ALERTS_ENABLED
              value: "1"
            - name: ALERT_STATE_FILE
              value: "out/alerts_state.json"
            - name: SMTP_HOST
              value: "smtp.gmail.com"
            - name: SMTP_PORT
              value: "587"
            - name: SMTP_USE_TLS
              value: "1"
