apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: continuum-app
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 3000
