name: CI-GHCR
on:
  push:
    branches: [main]
    paths:
      - Development/Sprint-4/code/**
      - Development/Sprint-4/k8s/**
      - .github/workflows/**

permissions:
  contents: read
  packages: write

env:
  GHCR_IMAGE_PREFIX: ghcr.io/${{ github.repository_owner }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build & Push Backend
        run: |
          docker buildx build \
            -t $GHCR_IMAGE_PREFIX/backend:${{ github.sha }} \
            -t $GHCR_IMAGE_PREFIX/backend:latest \
            --push Development/Sprint-4/code/backend

      - name: Build & Push Frontend
        run: |
          docker buildx build \
            --build-arg NEXT_PUBLIC_API_URL=/api \
            -t $GHCR_IMAGE_PREFIX/frontend:${{ github.sha }} \
            -t $GHCR_IMAGE_PREFIX/frontend:latest \
            --push Development/Sprint-4/code/frontend
